pds_validate_ecr_image_path = ""
pds_validate_cloudwatch_logs_group = "/ecs/validate"
efs_file_system_id = ""
pds_validate_data_access_point_id = ""
ecs_task_role_arn = ""
ecs_task_execution_role_arn = ""
