name: Auto-add Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    uses: NASA-PDS/.github/.github/workflows/add-issue-to-project.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
      # Update project_numbers below based on your needs
      # Single project: project_numbers: "6"
      # Multiple projects: project_numbers: "6,22"
      project_numbers: "6"
    secrets:
      # IMPORTANT: GITHUB_TOKEN does not have permission for org projects
      # You must create a PAT with 'project' scope and add it as ORG_PROJECT_PAT
      # See workflow-templates/README.md for setup instructions
      gh_token: ${{ secrets.ORG_PROJECT_PAT }}
