name: Issue Project Automation

on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  # When an issue is opened, add it to default project(s)
  add-new-issue-to-project:
    if: github.event.action == 'opened'
    uses: NASA-PDS/.github/.github/workflows/add-issue-to-project.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
      # Update project_numbers below based on your needs
      # Single project: project_numbers: "6"
      # Multiple projects: project_numbers: "6,22"
      project_numbers: "6"
    secrets:
      # IMPORTANT: GITHUB_TOKEN does not have permission for org projects
      # You must create a PAT with 'project' scope and add it as ORG_PROJECT_PAT
      # See workflow-templates/README.md for setup instructions
      gh_token: ${{ secrets.ORG_PROJECT_PAT }}

  # When a label is added or removed, handle build labels and sprint-backlog automation
  handle-label:
    if: github.event.action == 'labeled' || github.event.action == 'unlabeled'
    uses: NASA-PDS/.github/.github/workflows/label-to-project.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
      label_name: ${{ github.event.label.name }}
      action: ${{ github.event.action }}
    secrets:
      gh_token: ${{ secrets.ORG_PROJECT_PAT }}
